[package]
name = "yaml-schema"
version = "0.9.3"
edition = "2024"
description = "A YAML schema validator"
license = "MIT"
repository = "https://github.com/yaml-schema/yaml-schema"
documentation = "https://docs.rs/yaml-schema"
readme = "README.md"
homepage = "https://github.com/yaml-schema/yaml-schema"
exclude = [
    ".github/*"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.6.6", features = ["cargo", "derive"] }
env_logger = "0.11.11"
eyre = "0.6.14"
hashlink = "0.12.2"
jsonptr = "0.8.2"
log = "0.4.21"
ordered-float = "5.5.0"
regex = "1.10.4"
reqwest = { version = "0.12.22", features = ["blocking", "json", "rustls-tls"], default-features = false }
saphyr = "0.0.12"
serde_json = "~1.0.151"
thiserror = "2.0"
url = "2.5.8"

[dev-dependencies]
assert_cmd = "2.2.2"
tempfile = "3.27.0"
boon = "0.6.1"
criterion = "0.8.2"
ctor = "1.0.13"
cucumber = "0.23.0"
serde_json = "~1.0"
serde_yaml = "0.9.34"
tokio = { version = "1.53.1", features = ["full"] }

[[test]]
name = "features"
harness = false

[lints.clippy]
unwrap_used = "deny"

[[bench]]
name = "ys_vs_boon"
harness = false
